language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
    - j.bernal@upm.es
script:
# Unit Test & Integration Test
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
# Calidad codigo: Sonarcloud
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=miw-upm-github -Dsonar.login=$SONAR
